name: Android APK (Kivy/Buildozer)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull Buildozer image
        run: |
          DOCKER_BUILDKIT=0 docker pull kivy/buildozer

      - name: Build debug APK
        run: |
          DOCKER_BUILDKIT=0 docker run --rm \
            -v "${{ github.workspace }}:/home/buildozer/build" \
            -w /home/buildozer/build/kivy \
            kivy/buildozer \
            buildozer -v android debug
            
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: kivy/bin/*.apk
