name: Android APK (Kivy/Buildozer, no Docker)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            openjdk-17-jdk git zip unzip build-essential \
            libffi-dev libssl-dev zlib1g-dev libltdl-dev \
            python3-setuptools

      - name: Create venv and install Buildozer
        working-directory: kivy
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install cython==0.29.37 buildozer

      - name: Build debug APK
        working-directory: kivy
        run: |
          source .venv/bin/activate
          buildozer -v android debug

      # Optional diagnostics to reveal where Buildozer placed the Gradle dist
      - name: Show Buildozer output paths
        working-directory: kivy
        run: |
          echo "Listing .buildozer/android/platform ..."
          find .buildozer/android/platform -maxdepth 6 -type d -name dists -print -exec ls -la {} \; || true
          echo "Any build.gradle files?"
          find .buildozer -maxdepth 8 -type f -name build.gradle -print || true

      # Zip and upload the Gradle project (dist) regardless of ABI subfolder naming
      - name: Pack Gradle dist
        working-directory: kivy
        run: |
          set -e
          DIST=$(ls -d .buildozer/android/platform/build-*/dists/* | head -n1)
          echo "Dist path: $DIST"
          mkdir -p dist-upload
          zip -r dist-upload/gradle-dist.zip "$DIST"

      - name: Upload Gradle dist
        uses: actions/upload-artifact@v4
        with:
          name: gradle-dist
          path: kivy/dist-upload/gradle-dist.zip

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: kivy/bin/*.apk
